# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddf18b904857e669d4c7c2714af1956e3dea1c84b81b33a5ed9bcfde20db139dc6cdaf1de1bd75b11d4c1e4f52d3565574ff38751a6e5d566c0829a6dbe6522c

test:
  secret_key_base: 41893270ce3ec35cfc413a7f6a862caf6c1f29d87d50b173b2821118700303234a6a0a4402baa84e1f770227c92cc8740ee2c908dd20730f91572a7bbf5c59d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
